# Generated by Django 4.2.11 on 2025-04-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='sem_nome', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=100),
        ),
    ]
