# Generated by Django 4.2.11 on 2025-05-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_django', '0002_usuario_nome_alter_usuario_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
