# Generated by Django 4.2.11 on 2025-05-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_django', '0004_produto_imagem_alter_produto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to='produtos/'),
        ),
    ]
